### ISSUE TITLE
Possible to redirect firmware download to custom firmware??

### ISSUE THREAD

**Issue by mkormendy** [insertjokehere/homemate-bridge#11]
So when we redirect all traffic for homemate.orvibo.com, TCP port 10001, to the machine running the bridge by overriding the DNS records on our routers -- I'm wondering if we can also trigger the outlets to download and install a new firmware from the machine running the bridge as well?

**Comment by mkormendy** [comment]
Guess this project is defunct.

**Comment by insertjokehere** [comment]
Hey Mike,

Sorry for the radio silence on this. Yes, the project is effectively unmaintained at this point; I'll update the readme to reflect this.

Thanks,
Will
