### ISSUE TITLE
Can't find key on new application

### ISSUE THREAD

**Issue by rob1nzon** [insertjokehere/homemate-bridge#2]
I try find key in new application and can't do it. What you know about this?

**Comment by insertjokehere** [comment]
After you install homemate-bridge, you need to run download `http://www.orvibo.com/software/android/kepler.apk` and run `homemate-bridge-seed-keyfile kepler.apk --keys-file keys.json`. You then can use this keys file with the main `homemate-bridge` by passing `--keys-file` when running it

**Comment by rob1nzon** [comment]
Yes this it work. But i try do something with new application HomeMate and this is not work.

**Comment by mkormendy** [comment]
@rob1nzon Use the application that he has provided the link for. Don't use the HomeMate application - it doesn't have any part in this process.

**Comment by mkormendy** [comment]
@insertjokehere can we close this?
