### ISSUE TITLE
Use without Home Assistant?

### ISSUE THREAD

**Issue by mkormendy** [insertjokehere/homemate-bridge#5]
I'm guessing any mqtt capable application could control this, besides Home Assistant?

**Comment by insertjokehere** [comment]
Yep, absolutely. The payload that it sends to the MQTT conforms to the format that [HomeAssistant requires](https://www.home-assistant.io/docs/mqtt/discovery/) - as long as the client can consume those messages, and publish messages in the right format to control the switch it should just work

**Comment by mkormendy** [comment]
I'd like to keep this post available for others that want to use this with a different MQTT client. Can you post the formats and the topic structure?

**Comment by mkormendy** [comment]
BUMP

**Comment by mkormendy** [comment]
Well I managed to figure out the basics, and using the following commands:

PUB TOPIC: homeassistant/switch/IP-ADDRESS/command
SEND MESSAGE: ON or OFF

SUB TOPIC: homeassistant/switch/IP-ADDRESS/state
RETURNS: ON or OFF
